classDiagram

    Hotel o-- HotelLocation
    Hotel *-- Habitacion
    class Hotel
    Hotel: +HotelLocation
    Hotel: +Habitacion

    class HotelLocation
    HotelLocation: +ubicacion

    Persona <|-- Huesped 
    Persona <|-- Recepcionista
    Persona <|-- Gerente
    Persona <|-- AmaDeLlaves
    Persona <|-- Mozo

    class Persona 
    Persona: +nombre
    Persona: +apellido
    Persona: +domicilio

    Habitacion o-- RoomBooking
    Habitacion o-- RoomHouseKeeping
    Habitacion o-- RoomCharge
    Habitacion --o RoomKey
    Habitacion o-- ServicioLimpieza
    Habitacion o-- Mozo
    Habitacion *-- Estandar
    Habitacion *-- Lujo
    Habitacion *-- SuiteFamiliar

    class Habitacion
    Habitacion: +numHabitacion
    Habitacion: +tipoHabitacion
    Habitacion: +precioDeReserva
    Habitacion: +disponibilidad

    Cuenta o-- Notificacion
    Cuenta o-- Factura

    class Cuenta
    Cuenta: +tipoCuenta

    class Gerente
    Gerente: +registroCuenta()
    Gerente: +agregarEmpleado()

    Huesped --o Cuenta

    class Huesped
    Huesped: +buscar()
    Huesped: +reservar()

    class AmaDeLlaves
    AmaDeLlaves: +agregarRegistro()

    Recepcionista --o Cuenta
    Recepcionista o-- Pago

    class Recepcionista
    Recepcionista: +agregarHabitacion()
    Recepcionista: +crearReserva()
    Recepcionista: +cancelarReserva()
    Recepcionista: +checkIn()
    Recepcionista: +checkOut()

    ServicioLimpieza --o Cuenta
    ServicioLimpieza o-- AmaDeLlaves

    class ServicioLimpieza
    ServicioLimpieza: +seguimientoRegistro()

    class RoomBooking 
    RoomBooking: +gestionReserva()

    class Notificacion
    Notificacion: +notificacion

    class RoomHouseKeeping
    RoomHouseKeeping: +registroHabitaciones()

    RoomCharge --* Alimentos
    RoomCharge --* ServicioHabitacion
    RoomCharge --* Comodidades

    class RoomCharge
    
    RoomCharge: +TipoServicio

    class Factura
    Factura: +idFactura
    Factura: +nombre
    Factura: +domicilio
    Factura: +total
    Factura: +cargoHabitacion

    class RoomKey 
    RoomKey: +idLlave

    class Pago
    Pago: +efectivo
    Pago: +credito
    Pago: +cheque

    class ReservaHistorial
    ReservaHistorial: +que
    ReservaHistorial: +quien
    ReservaHistorial: +fecha

    Reserva --o ReservaHistorial

    class Reserva
    Reserva: +estado
    Reserva: +fechaReserva
    Reserva: +fechaHospedaje
    Reserva: +tipoHabitacion
    Reserva: +huesped
    Reserva: +cancelacion()

    class Estandar

    class Lujo

    class SuiteFamiliar

    class Alimentos

    class ServicioHabitacion

    class Comodidades

    class Mozo
    Mozo: +agregarRegistroH

    Usuario o-- AmaDeLlaves
    Usuario o-- Mozo 
    Usuario o-- Recepcionista
    Usuario o-- Invitado
    Usuario o-- Gerente
    
    class Usuario
    Usuario: +email

    Sistema --* Hotel
    Sistema --o Reserva
    Sistema --o Huesped
    Sistema --o Usuario
    Sistema --o ServicioLimpieza
    Sistema --o ReservaHistorial
    Sistema --o Habitacion

    class Sistema
    Sistema: +Usuario
    Sistema: +Habitacion
    Sistema: +Reserva
    Sistema: +ReservaHistorial
    Sistema: +ServicioLimpieza
    Sistema: +Huesped
    Sistema: +agregarHabitacion()
    Sistema: +buscarHabitacion()
    Sistema: +eliminarHabitacion()
    Sistema: +editarHabitacion()
    Sistema: +registrarCuenta()
    Sistema: +cancelarCuenta()
    Sistema: +reservarHabitacion()
    Sistema: +checkIn()
    Sistema: +checkOut()
    Sistema: +agregarGasto()
    Sistema: +actualizarRegistroDeLimpieza()
    Sistema: +reembolso()